// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'8d99b35d86659781481ae5992f39f278056b0907328e4b7d2145873a2ac84a1f'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Bairro: {
      readonly idBairro: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<50>;
    };
    readonly Caracteristica: {
      readonly idCaracteristica: CodecTypes['pg/int4@1']['output'];
      readonly descricao: Varchar<100> | null;
    };
    readonly Empresa: {
      readonly idEmpresa: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<150>;
      readonly cnpj: Varchar<18>;
      readonly telefone: Varchar<20> | null;
      readonly email: Varchar<150> | null;
    };
    readonly Imovel: {
      readonly idImovel: CodecTypes['pg/int4@1']['output'];
      readonly valor: CodecTypes['pg/numeric@1']['output'];
      readonly cliente: Varchar<100> | null;
      readonly telefone: Varchar<20> | null;
      readonly dataCapt: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly referencia: Varchar<200> | null;
      readonly status: Varchar<30> | null;
      readonly usuarioId: CodecTypes['pg/int4@1']['output'] | null;
      readonly empresaId: CodecTypes['pg/int4@1']['output'] | null;
      readonly criadoPorId: CodecTypes['pg/int4@1']['output'] | null;
      readonly bairroId: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly ImovelCaracteristica: {
      readonly quantidade: CodecTypes['pg/int4@1']['output'] | null;
      readonly imovelId: CodecTypes['pg/int4@1']['output'];
      readonly caracteristicaId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Usuario: {
      readonly idUsuario: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<150>;
      readonly email: Varchar<150>;
      readonly cpf: Varchar<11> | null;
      readonly cnpj: Varchar<18> | null;
      readonly telefone: Varchar<20> | null;
      readonly senha: Varchar<255>;
      readonly dataNasc: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly instagram: Varchar<30> | null;
      readonly empresaId: CodecTypes['pg/int4@1']['output'] | null;
      readonly tipoUsuario: 'ADMIN' | 'CORRETOR' | 'CORRETOR_INDIVIDUAL';
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Bairro: {
      readonly idBairro: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Caracteristica: {
      readonly idCaracteristica: CodecTypes['pg/int4@1']['input'];
      readonly descricao: CodecTypes['sql/varchar@1']['input'] | null;
    };
    readonly Empresa: {
      readonly idEmpresa: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly cnpj: CodecTypes['sql/varchar@1']['input'];
      readonly telefone: CodecTypes['sql/varchar@1']['input'] | null;
      readonly email: CodecTypes['sql/varchar@1']['input'] | null;
    };
    readonly Imovel: {
      readonly idImovel: CodecTypes['pg/int4@1']['input'];
      readonly valor: CodecTypes['pg/numeric@1']['input'];
      readonly cliente: CodecTypes['sql/varchar@1']['input'] | null;
      readonly telefone: CodecTypes['sql/varchar@1']['input'] | null;
      readonly dataCapt: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly referencia: CodecTypes['sql/varchar@1']['input'] | null;
      readonly status: CodecTypes['sql/varchar@1']['input'] | null;
      readonly usuarioId: CodecTypes['pg/int4@1']['input'] | null;
      readonly empresaId: CodecTypes['pg/int4@1']['input'] | null;
      readonly criadoPorId: CodecTypes['pg/int4@1']['input'] | null;
      readonly bairroId: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly ImovelCaracteristica: {
      readonly quantidade: CodecTypes['pg/int4@1']['input'] | null;
      readonly imovelId: CodecTypes['pg/int4@1']['input'];
      readonly caracteristicaId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Usuario: {
      readonly idUsuario: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly cpf: CodecTypes['sql/varchar@1']['input'] | null;
      readonly cnpj: CodecTypes['sql/varchar@1']['input'] | null;
      readonly telefone: CodecTypes['sql/varchar@1']['input'] | null;
      readonly senha: CodecTypes['sql/varchar@1']['input'];
      readonly dataNasc: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly instagram: CodecTypes['sql/varchar@1']['input'] | null;
      readonly empresaId: CodecTypes['pg/int4@1']['input'] | null;
      readonly tipoUsuario: 'ADMIN' | 'CORRETOR' | 'CORRETOR_INDIVIDUAL';
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly bairro: {
      readonly id_bairro: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<50>;
    };
    readonly caracteristicas: {
      readonly descricao: Varchar<100> | null;
      readonly id_caracteristicas: CodecTypes['pg/int4@1']['output'];
    };
    readonly empresa: {
      readonly cnpj: Varchar<18>;
      readonly email: Varchar<150> | null;
      readonly id_empresa: CodecTypes['pg/int4@1']['output'];
      readonly nome: Varchar<150>;
      readonly telefone: Varchar<20> | null;
    };
    readonly IMCAR: {
      readonly id_caracteristicas: CodecTypes['pg/int4@1']['output'];
      readonly id_imovel: CodecTypes['pg/int4@1']['output'];
      readonly quantidade: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly imovel: {
      readonly cliente: Varchar<100> | null;
      readonly criado_por: CodecTypes['pg/int4@1']['output'] | null;
      readonly data_capt: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly id_bairro: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_empresa: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_imovel: CodecTypes['pg/int4@1']['output'];
      readonly id_usuario: CodecTypes['pg/int4@1']['output'] | null;
      readonly referencia: Varchar<200> | null;
      readonly status: Varchar<30> | null;
      readonly telefone: Varchar<20> | null;
      readonly valor: CodecTypes['pg/numeric@1']['output'];
    };
    readonly usuario: {
      readonly cnpj: Varchar<18> | null;
      readonly cpf: Varchar<11> | null;
      readonly data_nasc: CodecTypes['pg/date-temporal@1']['output'] | null;
      readonly email: Varchar<150>;
      readonly id_empresa: CodecTypes['pg/int4@1']['output'] | null;
      readonly id_usuario: CodecTypes['pg/int4@1']['output'];
      readonly instagram: Varchar<30> | null;
      readonly nome: Varchar<150>;
      readonly senha: Varchar<255>;
      readonly telefone: Varchar<20> | null;
      readonly tipo_usuario: 'ADMIN' | 'CORRETOR' | 'CORRETOR_INDIVIDUAL';
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly bairro: {
      readonly id_bairro: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
    };
    readonly caracteristicas: {
      readonly descricao: CodecTypes['sql/varchar@1']['input'] | null;
      readonly id_caracteristicas: CodecTypes['pg/int4@1']['input'];
    };
    readonly empresa: {
      readonly cnpj: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'] | null;
      readonly id_empresa: CodecTypes['pg/int4@1']['input'];
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly telefone: CodecTypes['sql/varchar@1']['input'] | null;
    };
    readonly IMCAR: {
      readonly id_caracteristicas: CodecTypes['pg/int4@1']['input'];
      readonly id_imovel: CodecTypes['pg/int4@1']['input'];
      readonly quantidade: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly imovel: {
      readonly cliente: CodecTypes['sql/varchar@1']['input'] | null;
      readonly criado_por: CodecTypes['pg/int4@1']['input'] | null;
      readonly data_capt: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly id_bairro: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_empresa: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_imovel: CodecTypes['pg/int4@1']['input'];
      readonly id_usuario: CodecTypes['pg/int4@1']['input'] | null;
      readonly referencia: CodecTypes['sql/varchar@1']['input'] | null;
      readonly status: CodecTypes['sql/varchar@1']['input'] | null;
      readonly telefone: CodecTypes['sql/varchar@1']['input'] | null;
      readonly valor: CodecTypes['pg/numeric@1']['input'];
    };
    readonly usuario: {
      readonly cnpj: CodecTypes['sql/varchar@1']['input'] | null;
      readonly cpf: CodecTypes['sql/varchar@1']['input'] | null;
      readonly data_nasc: CodecTypes['pg/date-temporal@1']['input'] | null;
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly id_empresa: CodecTypes['pg/int4@1']['input'] | null;
      readonly id_usuario: CodecTypes['pg/int4@1']['input'];
      readonly instagram: CodecTypes['sql/varchar@1']['input'] | null;
      readonly nome: CodecTypes['sql/varchar@1']['input'];
      readonly senha: CodecTypes['sql/varchar@1']['input'];
      readonly telefone: CodecTypes['sql/varchar@1']['input'] | null;
      readonly tipo_usuario: 'ADMIN' | 'CORRETOR' | 'CORRETOR_INDIVIDUAL';
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly bairro: {
              columns: {
                readonly id_bairro: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 50 };
                };
              };
              primaryKey: { readonly columns: readonly ['id_bairro'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly caracteristicas: {
              columns: {
                readonly id_caracteristicas: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly descricao: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 100 };
                };
              };
              primaryKey: { readonly columns: readonly ['id_caracteristicas'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly empresa: {
              columns: {
                readonly id_empresa: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 150 };
                };
                readonly cnpj: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 18 };
                };
                readonly telefone: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 20 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 150 };
                };
              };
              primaryKey: { readonly columns: readonly ['id_empresa'] };
              uniques: readonly [{ readonly columns: readonly ['cnpj'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly IMCAR: {
              columns: {
                readonly quantidade: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly id_imovel: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly id_caracteristicas: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id_imovel', 'id_caracteristicas'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'IMCAR_id_imovel_idx_0e32f531';
                  readonly prefix: 'IMCAR_id_imovel_idx';
                  readonly columns: readonly ['id_imovel'];
                  readonly unique: false;
                },
                {
                  readonly name: 'IMCAR_id_caracteristicas_idx_ce753735';
                  readonly prefix: 'IMCAR_id_caracteristicas_idx';
                  readonly columns: readonly ['id_caracteristicas'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'IMCAR';
                    readonly columns: readonly ['id_imovel'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'imovel';
                    readonly columns: readonly ['id_imovel'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'IMCAR';
                    readonly columns: readonly ['id_caracteristicas'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'caracteristicas';
                    readonly columns: readonly ['id_caracteristicas'];
                  };
                },
              ];
            };
            readonly imovel: {
              columns: {
                readonly id_imovel: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly valor: {
                  readonly nativeType: 'numeric';
                  readonly codecId: 'pg/numeric@1';
                  readonly nullable: false;
                };
                readonly cliente: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 100 };
                };
                readonly telefone: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 20 };
                };
                readonly data_capt: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
                readonly referencia: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 200 };
                };
                readonly status: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 30 };
                };
                readonly id_usuario: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly id_empresa: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly criado_por: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly id_bairro: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id_imovel'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'imovel_id_usuario_idx_00d592a0';
                  readonly prefix: 'imovel_id_usuario_idx';
                  readonly columns: readonly ['id_usuario'];
                  readonly unique: false;
                },
                {
                  readonly name: 'imovel_criado_por_idx_822a368b';
                  readonly prefix: 'imovel_criado_por_idx';
                  readonly columns: readonly ['criado_por'];
                  readonly unique: false;
                },
                {
                  readonly name: 'imovel_id_empresa_idx_328936e2';
                  readonly prefix: 'imovel_id_empresa_idx';
                  readonly columns: readonly ['id_empresa'];
                  readonly unique: false;
                },
                {
                  readonly name: 'imovel_id_bairro_idx_f10e2b14';
                  readonly prefix: 'imovel_id_bairro_idx';
                  readonly columns: readonly ['id_bairro'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'imovel';
                    readonly columns: readonly ['id_usuario'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id_usuario'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'imovel';
                    readonly columns: readonly ['criado_por'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id_usuario'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'imovel';
                    readonly columns: readonly ['id_empresa'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'empresa';
                    readonly columns: readonly ['id_empresa'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'imovel';
                    readonly columns: readonly ['id_bairro'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'bairro';
                    readonly columns: readonly ['id_bairro'];
                  };
                },
              ];
            };
            readonly usuario: {
              columns: {
                readonly id_usuario: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nome: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 150 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 150 };
                };
                readonly cpf: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 11 };
                };
                readonly cnpj: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 18 };
                };
                readonly telefone: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 20 };
                };
                readonly senha: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly data_nasc: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-temporal@1';
                  readonly nullable: true;
                };
                readonly instagram: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 30 };
                };
                readonly id_empresa: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly tipo_usuario: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'CORRETOR'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id_usuario'] };
              uniques: readonly [
                { readonly columns: readonly ['email'] },
                { readonly columns: readonly ['cpf'] },
                { readonly columns: readonly ['cnpj'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'usuario_um_admin_por_empresa_5216da59';
                  readonly prefix: 'usuario_um_admin_por_empresa';
                  readonly columns: readonly ['id_empresa'];
                  readonly where: "(tipo_usuario = 'ADMIN')";
                  readonly unique: true;
                },
                {
                  readonly name: 'usuario_id_empresa_idx_328936e2';
                  readonly prefix: 'usuario_id_empresa_idx';
                  readonly columns: readonly ['id_empresa'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'usuario';
                    readonly columns: readonly ['id_empresa'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'empresa';
                    readonly columns: readonly ['id_empresa'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly TipoUsuario: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ADMIN', 'CORRETOR', 'CORRETOR_INDIVIDUAL'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly empresa: { readonly namespace: 'public' & NamespaceId; readonly model: 'Empresa' };
    readonly usuario: { readonly namespace: 'public' & NamespaceId; readonly model: 'Usuario' };
    readonly bairro: { readonly namespace: 'public' & NamespaceId; readonly model: 'Bairro' };
    readonly imovel: { readonly namespace: 'public' & NamespaceId; readonly model: 'Imovel' };
    readonly caracteristicas: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Caracteristica';
    };
    readonly IMCAR: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ImovelCaracteristica';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Bairro: {
            readonly fields: {
              readonly idBairro: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 50 };
                };
              };
            };
            readonly relations: {
              readonly imoveis: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Imovel';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idBairro'];
                  readonly targetFields: readonly ['bairroId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'bairro';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idBairro: { readonly column: 'id_bairro' };
                readonly nome: { readonly column: 'nome' };
              };
            };
          };
          readonly Caracteristica: {
            readonly fields: {
              readonly idCaracteristica: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly descricao: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
            };
            readonly relations: {
              readonly imoveis: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ImovelCaracteristica';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idCaracteristica'];
                  readonly targetFields: readonly ['caracteristicaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'caracteristicas';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idCaracteristica: { readonly column: 'id_caracteristicas' };
                readonly descricao: { readonly column: 'descricao' };
              };
            };
          };
          readonly Empresa: {
            readonly fields: {
              readonly idEmpresa: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
              readonly cnpj: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 18 };
                };
              };
              readonly telefone: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
            };
            readonly relations: {
              readonly imoveis: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Imovel';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idEmpresa'];
                  readonly targetFields: readonly ['empresaId'];
                };
              };
              readonly usuarios: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idEmpresa'];
                  readonly targetFields: readonly ['empresaId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'empresa';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idEmpresa: { readonly column: 'id_empresa' };
                readonly nome: { readonly column: 'nome' };
                readonly cnpj: { readonly column: 'cnpj' };
                readonly telefone: { readonly column: 'telefone' };
                readonly email: { readonly column: 'email' };
              };
            };
          };
          readonly Imovel: {
            readonly fields: {
              readonly idImovel: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly valor: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/numeric@1' };
              };
              readonly cliente: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 100 };
                };
              };
              readonly telefone: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly dataCapt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly referencia: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 200 };
                };
              };
              readonly status: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 30 };
                };
              };
              readonly usuarioId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly empresaId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly criadoPorId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly bairroId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly bairro: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Bairro';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['bairroId'];
                  readonly targetFields: readonly ['idBairro'];
                };
              };
              readonly caracteristicas: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ImovelCaracteristica';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idImovel'];
                  readonly targetFields: readonly ['imovelId'];
                };
              };
              readonly criadoPor: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['criadoPorId'];
                  readonly targetFields: readonly ['idUsuario'];
                };
              };
              readonly empresa: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Empresa';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['empresaId'];
                  readonly targetFields: readonly ['idEmpresa'];
                };
              };
              readonly usuario: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Usuario';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['usuarioId'];
                  readonly targetFields: readonly ['idUsuario'];
                };
              };
            };
            readonly storage: {
              readonly table: 'imovel';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idImovel: { readonly column: 'id_imovel' };
                readonly valor: { readonly column: 'valor' };
                readonly cliente: { readonly column: 'cliente' };
                readonly telefone: { readonly column: 'telefone' };
                readonly dataCapt: { readonly column: 'data_capt' };
                readonly referencia: { readonly column: 'referencia' };
                readonly status: { readonly column: 'status' };
                readonly usuarioId: { readonly column: 'id_usuario' };
                readonly empresaId: { readonly column: 'id_empresa' };
                readonly criadoPorId: { readonly column: 'criado_por' };
                readonly bairroId: { readonly column: 'id_bairro' };
              };
            };
          };
          readonly ImovelCaracteristica: {
            readonly fields: {
              readonly quantidade: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly imovelId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly caracteristicaId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly caracteristica: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Caracteristica';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['caracteristicaId'];
                  readonly targetFields: readonly ['idCaracteristica'];
                };
              };
              readonly imovel: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Imovel';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['imovelId'];
                  readonly targetFields: readonly ['idImovel'];
                };
              };
            };
            readonly storage: {
              readonly table: 'IMCAR';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly quantidade: { readonly column: 'quantidade' };
                readonly imovelId: { readonly column: 'id_imovel' };
                readonly caracteristicaId: { readonly column: 'id_caracteristicas' };
              };
            };
          };
          readonly Usuario: {
            readonly fields: {
              readonly idUsuario: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nome: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 150 };
                };
              };
              readonly cpf: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 11 };
                };
              };
              readonly cnpj: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 18 };
                };
              };
              readonly telefone: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 20 };
                };
              };
              readonly senha: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly dataNasc: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-temporal@1' };
              };
              readonly instagram: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 30 };
                };
              };
              readonly empresaId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tipoUsuario: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly empresa: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Empresa';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['empresaId'];
                  readonly targetFields: readonly ['idEmpresa'];
                };
              };
              readonly imoveis: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Imovel';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idUsuario'];
                  readonly targetFields: readonly ['usuarioId'];
                };
              };
              readonly imoveisCriados: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Imovel';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['idUsuario'];
                  readonly targetFields: readonly ['criadoPorId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'usuario';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly idUsuario: { readonly column: 'id_usuario' };
                readonly nome: { readonly column: 'nome' };
                readonly email: { readonly column: 'email' };
                readonly cpf: { readonly column: 'cpf' };
                readonly cnpj: { readonly column: 'cnpj' };
                readonly telefone: { readonly column: 'telefone' };
                readonly senha: { readonly column: 'senha' };
                readonly dataNasc: { readonly column: 'data_nasc' };
                readonly instagram: { readonly column: 'instagram' };
                readonly empresaId: { readonly column: 'id_empresa' };
                readonly tipoUsuario: { readonly column: 'tipo_usuario' };
              };
            };
          };
        };
        readonly enum: {
          readonly TipoUsuario: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ADMIN'; readonly value: 'ADMIN' },
              { readonly name: 'CORRETOR'; readonly value: 'CORRETOR' },
              { readonly name: 'CORRETOR_INDIVIDUAL'; readonly value: 'CORRETOR_INDIVIDUAL' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
